name = "prompt-qa-copilot"
main = "src/worker.js"
compatibility_date = "2026-02-16"

[vars]
OPENAI_MODEL = "gpt-4.1-mini"
MOCK_AI = "false"
REQUIRE_PRO = "false"

[[kv_namespaces]]
binding = "LICENSES_KV"
id = "66845cb6e0a44775b3df941fb372aadf"
preview_id = "75e88888927d47c68563cf07e8479faa"
